baseURL = 'https://hyzendust.github.io'
languageCode = 'en-us'
title = 'Freedoms4'
theme = 'hugo-theme-yue'
publishDir = "docs"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
dateFormat = "Posted on: 2 January, 2006"
customCSS = ["css/custom.css"]

[params.author]
name = "Freedoms4"
email = "your-email@example.com"

[caches]
[caches.images]
dir = ':cacheDir/images'

[menu]

[[menu.main]]
identifier = "landing"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blogs"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
identifier = "services"
name = "Services"
url = "/services/"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"
